title: Ergonomia Visual para Idosos
description: Guia de parâmetros ergonômicos visuais para projetos que envolvem idosos.
theme: just-the-docs
search_enabled: false

url: https://ergonomiavisualparaidosos.github.io/
