title: Ergonomia Visual Para Idosos
description: Guia de parâmetros ergonômicos visuais para projetos que envolvem idosos.
theme: just-the-docs
search_enabled: false

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
